import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { build } from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DIST_DIR = path.resolve(__dirname, '../dist');
const SERVER_DIR = path.resolve(__dirname, '../.tmp-server');
const INDEX_HTML_PATH = path.join(DIST_DIR, 'index.html');

const SITE_URL = 'https://sahayasavari.dev';

const ROUTES = [
  { path: '/', canonical: `${SITE_URL}` },
  { path: '/projects', canonical: `${SITE_URL}/projects` },
  { path: '/resume', canonical: `${SITE_URL}/resume` },
  { path: '/blog', canonical: `${SITE_URL}/blog` },
  { path: '/recruiter', canonical: `${SITE_URL}/recruiter` },
  { path: '/ai', canonical: `${SITE_URL}/ai` },
  { path: '/projects/prepmind-ai', canonical: `${SITE_URL}/projects/prepmind-ai` },
  { path: '/projects/daily-spark', canonical: `${SITE_URL}/projects/daily-spark` },
  { path: '/projects/portfolio-website', canonical: `${SITE_URL}/projects/portfolio-website` }
];

async function prerender() {
  if (!fs.existsSync(INDEX_HTML_PATH)) {
    console.error(`Error: Base ${INDEX_HTML_PATH} does not exist. Run vite build first.`);
    process.exit(1);
  }

  console.log('Building server module for static HTML pre-rendering...');
  await build({
    build: {
      ssr: path.resolve(__dirname, '../src/entry-server.tsx'),
      outDir: SERVER_DIR,
      minify: false,
      emptyOutDir: true,
      rollupOptions: {
        output: {
          format: 'esm'
        }
      }
    },
    configFile: false
  });

  const serverBundlePath = path.join(SERVER_DIR, 'entry-server.js');
  const { render } = await import(pathToFileURL(serverBundlePath).href);

  const baseHtml = fs.readFileSync(INDEX_HTML_PATH, 'utf-8');

  console.log(`Starting SEO static HTML pre-rendering for ${ROUTES.length} routes...`);

  // Extract and inline primary stylesheet to eliminate render-blocking CSS network roundtrip
  let inlineStyleTag = '';
  const stylesheetMatch = baseHtml.match(/<link\b[^>]*rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*\/?>/i);
  if (stylesheetMatch) {
    const cssRelativePath = stylesheetMatch[1].replace(/^\//, '');
    const cssFullPath = path.join(DIST_DIR, cssRelativePath);
    if (fs.existsSync(cssFullPath)) {
      const cssContent = fs.readFileSync(cssFullPath, 'utf-8');
      inlineStyleTag = `<style id="critical-css">${cssContent}</style>`;
      console.log(`  [✓] Inlined critical CSS from ${cssRelativePath} (${cssContent.length} bytes) to eliminate render-blocking latency`);
    }
  }

  for (const route of ROUTES) {
    let html = baseHtml;

    // Eliminate render-blocking CSS by replacing external link with inlined critical styles
    html = html.replace(/(<link\b[^>]*rel=["']stylesheet["'][^>]*\/?>)\s*/gi, '');
    if (inlineStyleTag) {
      html = html.replace(/(<link rel="manifest"[^>]*>)/i, `$1\n    ${inlineStyleTag}`);
    }

    // Render React components to static HTML for this route
    let appHtml = '';
    let rendered = null;
    try {
      rendered = render(route.path);
      appHtml = rendered.html || '';
    } catch (err) {
      console.warn(`[Warning] Failed to render React tree for route ${route.path}:`, err);
    }

    // Extract head metadata tags generated by Helmet from appHtml
    const headTagMatches = [];

    // 1. Extract <title>
    if (rendered?.helmet?.title) {
      const titleTag = rendered.helmet.title.toString();
      if (titleTag) headTagMatches.push(titleTag);
    } else {
      appHtml = appHtml.replace(/<title>.*?<\/title>/gi, (match) => {
        headTagMatches.push(match);
        return '';
      });
    }

    // 2. Extract <meta ...>
    appHtml = appHtml.replace(/<meta\b[^>]*\/?>/gi, (match) => {
      headTagMatches.push(match);
      return '';
    });

    // 3. Extract <link rel="canonical" ...>
    appHtml = appHtml.replace(/<link\b[^>]*rel=["']canonical["'][^>]*\/?>/gi, (match) => {
      headTagMatches.push(match);
      return '';
    });

    // 4. Extract <script type="application/ld+json">...</script>
    appHtml = appHtml.replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, (match) => {
      headTagMatches.push(match);
      return '';
    });

    // Ensure all extracted head tags carry data-rh="true" so react-helmet-async adopts them seamlessly on client hydration
    const headHtml = headTagMatches.map(tag => {
      if (!tag.includes('data-rh=')) {
        return tag.replace(/<([a-z1-6]+)/i, '<$1 data-rh="true"');
      }
      return tag;
    }).join('\n    ');

    // Inject headHtml into <head>
    if (headHtml) {
      html = html.replace('</head>', `    ${headHtml}\n  </head>`);
    }

    // Inject clean appHtml into #root
    if (appHtml) {
      html = html.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);
    } else {
      console.error(`[Error] appHtml was empty for route ${route.path}!`);
    }

    // Update noscript block to be clean and informative
    const updatedNoscript = `<noscript><div style="padding:1.5rem;text-align:center;color:#fff;background:#000;font-family:sans-serif;"><p style="font-size:1.25rem;font-weight:700;margin:0 0 0.5rem;">Sahaya Savari - Portfolio</p><p>JavaScript is recommended for interactive animations. Full static page content is displayed above.</p></div></noscript>`;
    html = html.replace(/<noscript>[\s\S]*?<\/noscript>/gi, updatedNoscript);

    // Prevent Cloudflare Email Address Obfuscation from rewriting mailto links into /cdn-cgi/l/email-protection
    html = html.replace(/(<a\b[^>]*href=["']mailto:[^"']+["'][^>]*>[\s\S]*?<\/a>)/gi, '<!--email_off-->$1<!--/email_off-->');

    // Determine file output target
    if (route.path === '/') {
      fs.writeFileSync(INDEX_HTML_PATH, html, 'utf-8');
      console.log(`  [✓] Pre-rendered / -> dist/index.html (${appHtml.length} bytes body HTML)`);
    } else {
      const targetDir = path.join(DIST_DIR, route.path.replace(/^\//, ''));
      fs.mkdirSync(targetDir, { recursive: true });
      const targetFile = path.join(targetDir, 'index.html');
      fs.writeFileSync(targetFile, html, 'utf-8');
      console.log(`  [✓] Pre-rendered ${route.path} -> ${path.relative(DIST_DIR, targetFile)} (${appHtml.length} bytes body HTML)`);
    }
  }

  // Generate automated sitemap.xml in dist/
  const DEFAULT_LASTMOD = '2026-08-15';
  const sitemapEntries = ROUTES.map(r => `  <url>
    <loc>${r.canonical}</loc>
    <changefreq>${r.path === '/' || r.path === '/projects' || r.path === '/blog' ? 'weekly' : 'monthly'}</changefreq>
    <priority>${r.path === '/' ? '1.0' : r.path.startsWith('/projects') || r.path === '/blog' ? '0.9' : '0.8'}</priority>
    <lastmod>${r.lastmod || DEFAULT_LASTMOD}</lastmod>
  </url>`).join('\n');

  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries}
</urlset>\n`;

  fs.writeFileSync(path.join(DIST_DIR, 'sitemap.xml'), sitemapXml, 'utf-8');
  console.log(`  [✓] Generated automated dist/sitemap.xml (${ROUTES.length} routes)`);

  // Cleanup temporary server build directory
  try {
    fs.rmSync(SERVER_DIR, { recursive: true, force: true });
  } catch (e) {
    // Ignore cleanup error
  }

  console.log('SEO pre-rendering completed successfully!');
}

prerender();
